# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
array_1D= np.arange(0,10)
array_1D.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
array1= np.arange(0,10).reshape(2,5)
array2= np.ones(10).reshape(2,5)
array2= array2.astype('int')
np.vstack((array1,array2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:
np.hstack((array1,array2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
array= np.arange(0,10).reshape(2,5)
array.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
array3=np.arange(0,15).reshape(5,3)
array3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
array4= np.arange(1,26).reshape(5,5)
np.sqrt(array4)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595],
       [4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ]])

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
array5= np.arange(1,31).reshape(5,6)
array5.mean()

15.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
array5.std()

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [10]:
np.median(array5)


15.5

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
array5.transpose()

array([[ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29],
       [ 6, 12, 18, 24, 30]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
array6= np.arange(1,17).reshape(4,4)
np.trace(array6)   

34

## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
np.linalg.det(array6)

-1.820448242817726e-31

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
array7= np.arange(5)
per5=np.percentile(array7, 5)
per95=np.percentile(array7,95)
print("5th percentile: " + str(per5) + " and 95th percentile: " + str(per95))

5th percentile: 0.2 and 95th percentile: 3.8


## Question:15

### How to find if a given array has any null values?

In [15]:
array8= np.arange(0,5)
np.any(array8)

True