# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [2]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
null_vector=np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [4]:
vector=np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
vector.shape

(40,)

5. Print the type of the previous array in question 3

In [6]:
vector.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [7]:
np.__version__

'1.19.2'

In [8]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HP/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HP/anaconda3\\Library\\include']


7. Print the dimension of the array in question 3


In [9]:
vector.ndim

1

8. Create a boolean array with all the True values

In [10]:
np.ones(10, dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [11]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

10. Create a three dimensional array



In [12]:
np.array([[[1,2,3],[4,5,6],[7,8,9]]])

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [13]:
#method 1
vector[::-1] 
#method 2
np.flipud(vector) 

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

12. Create a null vector of size 10 but the fifth value which is 1 

In [14]:
#method 1
(np.arange(10) == 4).view(np.uint8)
#method 2 
(np.arange(10) == 4).astype(int)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [15]:
np.eye(3)
#also
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [16]:
arr = np.array([1, 2, 3, 4, 5])
arr. astype('float64')

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [17]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [18]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
combine_arr=arr1+arr2
combine_arr

array([[ 1.,  6.,  4.],
       [11.,  7., 18.]])

17. Extract all odd numbers from arr with values(0-9)

In [19]:
odd_array=arr[arr%2 != 0]
#also
odd_array=arr[arr%2 == 1]
odd_array

array([1, 3, 5])

18. Replace all odd numbers to -1 from previous array

In [20]:
arr = np.array([1, 2, 3, 4, 5])
np.where(arr%2 == 1, -1, arr)


array([-1,  2, -1,  4, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [21]:
arr = np.arange(10)
arr[5:9]=12
arr  

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [22]:
arr_2D= np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2D[0,0:]=1
arr_2D[2,0:]=1
arr_2D[1,0]=1
arr_2D[1,2]=1
arr_2D[1,1]=0
arr_2D

array([[1, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [23]:
arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [24]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0,:]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [25]:
arr2d_value=np.arange(10).reshape(5,2)
print(arr2d_value)
arr2d_value[0]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([0, 1])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [26]:
arr2d_value=np.arange(10).reshape(5,2)
print(arr2d_value)
arr2d_value[1,1]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [27]:
arr2d_value=np.arange(10).reshape(5,2)
print(arr2d_value)
arr2d_value[0:2,]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


array([[0, 1],
       [2, 3]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
matrix=np.random.rand(10,10)
print(matrix)
print("minimum value is", np.min(matrix))
print("maximum value is", np.max(matrix))

[[0.13425884 0.4161563  0.94106587 0.73104861 0.02104451 0.74429884
  0.23742863 0.32726599 0.33352519 0.35600765]
 [0.12522952 0.12612145 0.04830213 0.87263505 0.54552042 0.98730944
  0.73242711 0.39029044 0.86462823 0.00191864]
 [0.25244583 0.89004617 0.88700513 0.08900443 0.27390809 0.20721662
  0.24947414 0.50785434 0.10080601 0.29147076]
 [0.49998079 0.3192863  0.07860315 0.18101675 0.84508458 0.36981261
  0.20310485 0.74199977 0.05219489 0.53057042]
 [0.84395891 0.6931885  0.93047531 0.94685978 0.63460723 0.63581571
  0.07619994 0.22959544 0.82904565 0.02203434]
 [0.03164261 0.51599234 0.38975044 0.1448534  0.34889503 0.23864614
  0.35489104 0.82190997 0.04842917 0.98070313]
 [0.42290651 0.91439441 0.35232034 0.96801185 0.80396434 0.49064204
  0.57935183 0.77792847 0.96525173 0.42873103]
 [0.57015746 0.62405365 0.06555614 0.47532156 0.16265802 0.18246786
  0.9575664  0.88071099 0.64254156 0.74845456]
 [0.29729488 0.00257477 0.58143047 0.21599777 0.30862808 0.73649158
  0.9494641 

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [30]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.arange(len(a))[a==b]

array([1, 3, 5, 7])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [68]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)
data[names != 'Will']

[[-0.22711902  0.29002147 -1.37034406  1.19767152]
 [-0.79295748 -1.18031027 -0.62021675 -0.6568    ]
 [ 2.338453    0.93441521 -0.32646434  0.6250444 ]
 [ 0.58232313 -1.53657332 -0.74286859  1.27458039]
 [-1.28017564 -0.26851944 -0.42214876 -0.56045488]
 [ 0.34048599 -0.15248234  0.26354416 -1.70485187]
 [-0.42843816  0.62111879 -0.81088827  0.45633632]]


array([[-0.22711902,  0.29002147, -1.37034406,  1.19767152],
       [-0.79295748, -1.18031027, -0.62021675, -0.6568    ],
       [ 0.58232313, -1.53657332, -0.74286859,  1.27458039],
       [ 0.34048599, -0.15248234,  0.26354416, -1.70485187],
       [-0.42843816,  0.62111879, -0.81088827,  0.45633632]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [67]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
mask =(names != 'Will') & (names != 'Joe')
print(data)
data[mask]

[[ 0.3027823  -0.34880239 -0.73592421  0.64101979]
 [ 1.45045194  0.5923186  -0.2006449  -0.44222849]
 [ 0.83997941 -0.44918937 -0.38637638  1.50212076]
 [ 1.10274882 -0.58598485 -0.11178003  0.7008069 ]
 [ 0.56476556 -0.49551214 -0.07137978  1.08558709]
 [ 0.69007908  1.11978818 -1.16537574  0.75400771]
 [-0.66985593 -0.65527768 -0.37077647 -1.26570639]]


array([[ 0.3027823 , -0.34880239, -0.73592421,  0.64101979],
       [ 1.10274882, -0.58598485, -0.11178003,  0.7008069 ]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [33]:
np.arange(1,16).reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [34]:
q32_array=np.arange(1,17).reshape(2,2,4)
q32_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [69]:
np.swapaxes(q32_array,0,1)


array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [37]:
arr_sqr=np.arange(10)
sq=np.sqrt(arr_sqr)
np.where(sq<0.5,0, sq)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [ ]:
random_1=np.random.randn(12)
random_2=np.random.randn(12)
print (random_1, random_2)
np.maximum(random_1,random_2)
#aslo
np.where(random_1 >random_2, random_1, random_2)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names=np.unique(names)
np.sort(unique_names)

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [74]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [109]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray_new)
newColumn = np.array([[10,10,10]])
sampleArray_new= np.delete(sampleArray, 2, 1)
np.insert(sampleArray_new, 1, newColumn, axis = 1 ) 

[[34 43]
 [82 22]
 [53 94]]


array([[34, 10, 43],
       [82, 10, 22],
       [53, 10, 94]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [71]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [70]:
matrix=np.random.rand(2,10)
print(matrix)
matrix.cumsum()

[[0.64553856 0.32598452 0.36718572 0.82954548 0.78181077 0.57477941
  0.38421377 0.6581253  0.21886295 0.60006895]
 [0.54447948 0.98469844 0.51082123 0.35718635 0.92106596 0.46718319
  0.3667155  0.60097119 0.71757985 0.73329525]]


array([ 0.64553856,  0.97152309,  1.33870881,  2.16825429,  2.95006507,
        3.52484448,  3.90905824,  4.56718354,  4.78604649,  5.38611544,
        5.93059492,  6.91529336,  7.42611458,  7.78330094,  8.7043669 ,
        9.17155009,  9.53826559, 10.13923678, 10.85681663, 11.59011188])